#!/usr/bin/env python3
import sys

# Ajout de la fonction principale
def main():
    if len(sys.argv) >= 2 :
        #Ouverture en écriture du fichier 
        fichier = open("./results/"+sys.argv[1]+"-result.txt","w")
    while True:
        try:
            if sys.stdin.isatty():
                # Invite l'utilisateur à entrer une expression
                user_input = input("> ")
            else:
                # Lecture depuis l'entrée non interactive : "echo"
                user_input = input()

            # Évalue l'expression entrée
            result = eval(user_input)


            if len(sys.argv) >= 2 :
                #Ecriture des resultats dans le fichier  
                fichier.write(str(result)+"\n")
            else : 
                # Afficher le résultat
                print(result)

        except EOFError:
            # Gère le Ctrl+D 
            break

        except Exception as e:
            # Gère les erreurs de calcul
            print(f"Erreur de calcul: {str(e)}")

    # Si en mode interactif, afficher le message de fin
    if sys.stdin.isatty():
        print("\nFin des calculs :)")

    if len(sys.argv) >= 2 :
        fichier.close()
if __name__ == "__main__":
    # Si en mode interactif, exécuter la fonction main()
    main()
