#!/usr/bin/env python3



#ajout de la fonction principal
def main():
    while True:
        try:
            # Invite l'utilisateur à entrer une expression 
            user_input = input("> ")
            
            # Évalue l'expression entrée 
            result = eval(user_input)
            
            # Afficher le résultat
            print(result)

        except EOFError:
            # Gère le Ctrl+D 
            break
            
        except Exception as e:
            # Gére les erreurs de calcul 
            print(f"Erreur de calcul: {str(e)}")

    # Message de fin
    print("\nFin des calculs :)")

if __name__ == "__main__":
    # Si en mode interactif, exécuter la fonction main()
    main()